### ISSUE TITLE
Expired payment: order notification email sent

### ISSUE THREAD

**Issue by Echron** [MultiSafepay/Magento2Msp#10]
When a payment is expired the customer receives a notification email. We guess the bug is in  source/vendor/multisafepay/magento2msp/Model/Connect.php line 719:

` if (($order_email == "after_transaction" && $status != "initialized" && $status != "expired" && !$order->getEmailSent()) ||
                ($payment->getMethodInstance()->_code == 'mspbanktransfer' && !$order->getEmailSent()) ||
                ($status == "expired" && isset($this->_client->orders->data->transaction_id))
        ) {
            
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $objectManager->create('Magento\Sales\Model\OrderNotifier')->notify($order);
}`

When the payment is expired and the transaction has an id, the customer is notified, this is not the expected behaviour.

**Comment by JonkRuud** [comment]
Hello @Echron  sorry for the late response. We will look at this asap and provide you with a solution.

**Comment by JonkRuud** [comment]
@Echron can you tell me where the option "When send the order confirmation e-mail" is set to? When its set to "After transaction" this seems to be correct. When its set to "After paid transaction" then its not. I do see it going wrong with the second one so we will fix that one.

**Comment by Echron** [comment]
@JonkRuud It's set to "After paid transaction". 

Following happens:
- customer creates an order => no email is send
- payment expires => email is send

**Comment by JonkRuud** [comment]
@Echron  it should now be fixed with the last commit, can you confirm it works for you?

**Comment by cherreman** [comment]
@JonkRuud We fixed it ourselves in the exact same way so I'm sure this will work.
