### ISSUE TITLE
[PLGMAGTWOS-495] Tier prices in shoppingcart checkoutdata

### ISSUE THREAD

**Issue by Hexmage** [MultiSafepay/Magento2Msp#106]
In magento 2 configurable product tier prices are not used, but if they are filled for whatever reason (like a migration from magento 1) they could be used to calculated the shoppingCart unit price.

In Model/Connect.php 653-666 and 807-822 the variable $proddata is the product data of the configurable product instead of the simple product. This results in the code trying to get the tier prices of the configurable product, which would normally fail because Magento 2 doesn't allow prices on configurable products. But in case of bad data, this could result in the wrong price being send to MSP.

This code should not be necessary in the first place, because the quote_item will already have the tierprice associated with it at this point.

**Comment by Jasper-MultiSafepay** [comment]
Thank you for reporting this issue.
We will try to reproduce this and see if we can indeed remove that part of the code

**Comment by thokiller** [comment]
@Jasper-MultiSafepay ,
I have a comparable issue. My shop uses a custom product type. The base price of the product is 0 euro`s. The customer can add options. the options give the base product in the shop a price depending on the options chosen.

My temporary solutions is to disable the parts with the tier prices. 
https://github.com/MultiSafepay/Magento2Msp/blob/master/Model/Connect.php#L783-L797
And
https://github.com/MultiSafepay/Magento2Msp/blob/master/Model/Connect.php#L808-L822

I will add below a sample from the debugger log.
[Example.txt](https://github.com/MultiSafepay/Magento2Msp/files/3824878/Example.txt)

**Comment by Jasper-MultiSafepay** [comment]
@thokiller 
Currently investigating, we will remove the tierprices parts.
It's added on our develop branch e6f7af9f134a2dff4337b6d17315609f66e6df2d
We're preparing a new release where this will be included.
