### ISSUE TITLE
Checkout gives jquery/ui warning

### ISSUE THREAD

**Issue by DerFrenk** [MultiSafepay/Magento2Msp#116]
Hi,

We've recently upgraded our Magento2 installation from 2.3.1 to 2.3.4. When I now open the checkout and go to the payment step, the following message is visible in the devtools console:

![image](https://user-images.githubusercontent.com/6249209/75879097-089f3180-5e1b-11ea-8b93-c6485c10e00f.png)

This is caused by the following line of code:
https://github.com/MultiSafepay/Magento2Msp/blob/master/view/frontend/web/js/view/payment/method-renderer/connect-method.js#L41

Magento splitted jQuery UI into multiple files like `jquery-ui-modules/core`, `jquery-ui-modules/widget`, etc. See https://github.com/magento/magento2/blob/2.4-develop/lib/web/jquery/compat.js for the full list of modules.

When `jquery/ui` is requested as dependency, `compat.js` will now be loaded instead. This compatibility file loads _all_ jquery-UI modules with separate requests, which hurts the performance of our checkout quite bad.

I'm not sure which jQuery UI modules you need for the connect-method.js file, so I decided to open an issue instead of a pull request. Could you please look into it? :)

**Comment by vinodsowdagar** [comment]
Hi @DerFrenk ,

Thank you for reporting this issue. 
The detailed explanation you provided will be of much help.

We will look into this as soon as possible and we will keep you updated while we are working on a solution.

**Comment by vinodsowdagar** [comment]
Hi @DerFrenk  ,

We looked in to this and we could safely remove the jquery/ui dependency. 
This was an old remnant that is not being used anymore. 

The change can be found in the following commit: 02b8dc3
We will give you an update when the change will be available in the next release.

**Comment by DerFrenk** [comment]
Nice, thanks! :)

**Comment by vinodsowdagar** [comment]
Hi @DerFrenk ,

We have released a new version of our extension which contains the fix you requested. more information can be found here:

https://github.com/MultiSafepay/Magento2Msp/releases/tag/1.10.0

We are closing this issue. If you still have questions or comments, feel free to start a new one.
