### ISSUE TITLE
no gateways are shown, No Payment method available.

### ISSUE THREAD

**Issue by akosglue** [MultiSafepay/Magento2Msp#119]
MSP 1.11.0 installed on Magento ver. 2.3.5
Test api key is filled in.
The Gateways tab shows no gateways at all, and on frontend the error "No Payment method available" is shown.
However, on the Settings tab, the list of payment methods is available.
(see screenshots)
Is this a bug?
<img width="1348" alt="Screenshot 2020-04-30 at 12 28 35" src="https://user-images.githubusercontent.com/17706334/80700511-249f1680-8ade-11ea-8f29-186e3c7b285d.png">
<img width="600" alt="Screenshot 2020-04-30 at 12 24 11" src="https://user-images.githubusercontent.com/17706334/80700520-27017080-8ade-11ea-8092-fab8c355f045.png">

**Comment by akosglue** [comment]
this is also in the system log when I try to list the gateways:
main.CRITICAL: Class Temando\Shipping\Model\Shipping\Carrier does not exist [] []

this is suspicious because magento comes without this module, there is module which removes the module:

    "name": "temando/module-shipping-remover",
    "description": "Removes Temando multi-carrier shipping extension from Magento 2",
    "version": "1.0.0",
    "replace": {
        "temando/module-shipping-m2": "*"
    },

**Comment by Jasper-MultiSafepay** [comment]
@akosglue 
Are you on 2.3.5 or 2.3.5-p1?
Currently unable to reproduce on a clean install on 2.3.5-p1
Tested with developer mode and with a composer install
```
composer require multisafepay/magento2msp
php bin/magento setup:upgrade
```

**Comment by akosglue** [comment]
It is 2.3.5. in production mode.
The problem was that I had a temando entry in the config.php file. It referenced the model
'model' => 'Temando\\Shipping\\Model\\Shipping\\Carrier',
and that caused the error. Now it is removed and the payment methods are listed. So everything works as expected.
