### ISSUE TITLE
Cart empty after canceling payment

### ISSUE THREAD

**Issue by marleenp1p5** [MultiSafepay/Magento2Msp#12]
Hi,

When I cancel the payment it clears the shopping cart. Your readme says it will not empty (or cancel) the order. I'm using MSP 1.3.0 and magento 2.1.6.

Hope you can fix this issue

Best regards,

**Comment by JonkRuud** [comment]
Hello,
Seems like this is happening on some installation and this is fixed in the current develop branch. If you create a support ticket for this by mailing to 'techsupport @ multisafepay.com' then our Tech support department can update your current plugin and resolve this.

**Comment by JonkRuud** [comment]
Hello, 
Not sure if you created a support ticket for this, but with the next release a change is added that fixes this issue. It can now be found within commit: https://github.com/MultiSafepay/Magento2Msp/commit/c7a216d1a25742adfe3d1ffeafb42521b5d75936
