### ISSUE TITLE
[SUPD-265] For discounts coupons it's requierd to apply customer tax before discount.

### ISSUE THREAD

**Issue by lpouwelse** [MultiSafepay/Magento2Msp#124]
In the release notes of version 1.0.6 the following is mentioned:
"Discounts/coupons did not yet get processed for Pay After Delivery/Klarna. This is now solved. Important: Tax settings should be set to: Apply Customer Tax= Before Discount, Apply Discount On Prices= Including tax. Using other settings results in a 1027 error because Tax can't be calculated based on the other settings."

Apply-ing taxes before discount is not desirable because you pay to many taxes when you do this. So the setting Apply Customer Tax should be After discount en this extension should support shild.

**Comment by vinodsowdagar** [comment]
Hi @lpouwelse ,

Thank you for bringing this to our attention.

We will look into this as soon as possible and we will keep you updated while we are trying to find a solution.

**Comment by Jasper-MultiSafepay** [comment]
@lpouwelse 
For now it seems to be not a plugin issue.
I see we have an internal ticket about your issue, so I'm closing this for now.
Our integration team is keeping contact with you.
