### ISSUE TITLE
[PLGMAGTWOS-645 ]Can not install on Magento 2.4

### ISSUE THREAD

**Issue by Hexmage** [MultiSafepay/Magento2Msp#128]
The module can't be installed on Magento 2.4 because of the increase version of the magento/framework.

**Comment by Jasper-MultiSafepay** [comment]
@Hexmage 
Confirmed, we are testing everything to see if nothing is broken on Magento 2.4.
I'm expecting an update on this tomorrow.

**Comment by onepack** [comment]
Hi Jasper, any update on this?

**Comment by Hexmage** [comment]
@onepack I believe they fixed it the 1.13.0 release.

**Comment by onepack** [comment]
@Hexmage Thank you for the fast reply. Very good news.
I will test the 1.13.0 release now.

**Comment by vinodsowdagar** [comment]
Hi @onepack and @Hexmage ,

We indeed released a new version of our extension which can be installed on Magento 2.4.
https://github.com/MultiSafepay/Magento2Msp/releases/tag/1.13.0

For now i will close this ticket. If you have another question, feel free to create a new issue. 
Thank you for your patience.
