### ISSUE TITLE
[PLGMAGTWOS-644] Bundle Items don't show up in MultiSafepay Control when placing an order.

### ISSUE THREAD

**Issue by Hexmage** [MultiSafepay/Magento2Msp#129]
In commit c8052f78c762690d11b8a83238d24c209b492090 the way bundle products were handled got changed. The result is that bundle products aren't exported at all anymore.

The reason for this is that the products attached to the bundle don't have a price. And because the main bundle product is now skipped as well, no bundle product info is send to the MSP backend.

The problem with the change is that the Bundle Product contains all the price info, but the attached Simples contain all the product info. So you need data from both, but as is the MSP backend can't properly display the relation between these.

**Comment by Hexmage** [comment]
As a sidenote the client for who I discovered this, doesn't want to show the content of the bundle because it is static. And only wants to show the bundle itself. So if would be great if this could be made configurable.

**Comment by Jasper-MultiSafepay** [comment]
@Hexmage 
This was added to prevent a bundled product to be added twice within the shopping cart.
I'll check what's happening here.

**Comment by Hexmage** [comment]
@Jasper-MultiSafepay 
As far as I could tell the function was only used to set the data that was send to MSP.

**Comment by Jasper-MultiSafepay** [comment]
@Hexmage 
I believe I can reproduce this with a bundle product with Dynamic Price set to Yes.
Could you confirm this on your side?

**Comment by Hexmage** [comment]
@Jasper-MultiSafepay 
I'm experiencing this with products with Dynamic Price set to No.

**Comment by Hexmage** [comment]
@Jasper-MultiSafepay 
But the attached simples still have a fixed price set for 0.

**Comment by vinodsowdagar** [comment]
Hi @Hexmage ,

This should be fixed now in the new version of our extension:
https://github.com/MultiSafepay/Magento2Msp/releases/tag/1.13.0

Please let us know if the change is working for you now.

**Comment by Hexmage** [comment]
@Vinod-MultiSafepay 
Looks like it's working now.

**Comment by vinodsowdagar** [comment]
@Hexmage ,

Great to hear that it is working now.

For now i will close this issue.
If you have another question or more feedback, feel free to create a new issue.
