### ISSUE TITLE
MSP doesn't work on M2.4

### ISSUE THREAD

**Issue by onepack** [MultiSafepay/Magento2Msp#130]
Endless spinner and error console message:

Uncaught SyntaxError: missing ) after argument list

https://domain.com/pub/static/version1597787892/frontend/provider/theme/en_US/MultiSafepay_Connect/js/view/payment/method-renderer/connect-method.js rule: 307

This is actually the line:
`'By registering your credentials, You can speed up your purchases. Because you don't need to fill in your credentials again'+`

But in module:
`$.mage.__("By registering your credentials, You can speed up your purchases. Because you don't need to fill in your credentials again") +`

All cache and pub dirs were deleted though...

I changed the line to "Because you do not" for testing and after that it worked after setup:update on dev environment.

I have the latest version of MSP installed via composer on DEV and Prod environments and both give this issue.

**Comment by onepack** [comment]
So I ended up escaping` \'` on line 307 in connect-method.js to get things working.

**Comment by Jasper-MultiSafepay** [comment]
@onepack 
Thanks for reporting, but I am unable to reproduce this.
But seeing how this function is no longer used, I have removed it for the next release.
