### ISSUE TITLE
Order cancellation event

### ISSUE THREAD

**Issue by egordm** [MultiSafepay/Magento2Msp#131]
In the last release code is updated to run the cancel call in order to emit the order cancellation events. (pr https://github.com/MultiSafepay/Magento2Msp/pull/125 and c8c14431094e7f56fb94f4e025f758f55f7e2edb)
There are still a few parts of the code that handle cancellation the previous way. Is it possible to apply a similar fix there too?
Parts in question:
https://github.com/MultiSafepay/Magento2Msp/blob/a63122083ddbc33bcf220691193a0b9d2c0b47ed/Controller/Fastcheckout/Cancel.php#L117
https://github.com/MultiSafepay/Magento2Msp/blob/0ca7cb37860ca5e41259c879fc2d272077f5dbb7/Model/Connect.php#L1306 and the ones below (4 occurences)

Thanks in advance.

**Comment by Ronald-MultiSafepay** [comment]
@EgorDm  
Thank you for reporting. We have created an internal task for this report and will try to review as soon as possible. 
Internal reference: PLGMAGTWOS-669

**Comment by Stanislau-MultiSafepay** [comment]
Hi! @EgorDm 

Unfortunately, this plugin is deprecated and we are not providing support for it anymore. Please, upgrade to our New Magento 2 plugin.

This issue has not occurred in the new plugin and the new plugin also has tons of other improvements.

I am closing this issue for now. If you have any more comments or questions, feel free to create a new issue in the new plugin repository.
