### ISSUE TITLE
Payment link is not output because a wrong data type

### ISSUE THREAD

**Issue by skynixukraine** [MultiSafepay/Magento2Msp#132]
To Reproduce request a payment link GET /rest/V1/multisafepay/mine/payment-url/<order-id>

Here https://github.com/MultiSafepay/Magento2Msp/blob/master/Model/PaymentUrl.php on line 73 it will always fail on validation. Because $customerId is INTEGER and  $order->getCustomerId() is STRING
A quick turnaround would be to do the following:

if ($customerId && $customerId !== (int)$order->getCustomerId()) {
            return '';
        }

**Comment by Jasper-MultiSafepay** [comment]
@skynixukraine 
I have a look at it in the current sprint.
For now you use the quick workaround, I will keep you updated on the progress

**Comment by Jasper-MultiSafepay** [comment]
@skynixukraine 
Confirmed, we will apply the same fix in the upcoming version
