### ISSUE TITLE
Get active methods

### ISSUE THREAD

**Issue by JoostWan** [MultiSafepay/Magento2Msp#136]
Magento 2 has a default function for get active payment methods. This can be done with this function;

**getActiveMethods()**

vendor/magento/module-payment/Model/Config.php

But this is not working for MultiSafePayment methods. Can this be fixed? Reports module uses this function for getting active payment methods for generate reports. 

```
 /**
     * Retrieve active system payments
     *
     * @return array
     * @api
     */
    public function getActiveMethods()
    {
        $methods = [];
        foreach ($this->_scopeConfig->getValue('payment', ScopeInterface::SCOPE_STORE, null) as $code => $data) {
            if (isset($data['active'], $data['model']) && (bool)$data['active']) {
                /** @var MethodInterface $methodModel Actually it's wrong interface */
                $methodModel = $this->_paymentMethodFactory->create($data['model']);
                $methodModel->setStore(null);
                if ($methodModel->getConfigData('active', null)) {
                    $methods[$code] = $methodModel;
                }
            }
        }
        return $methods;
    }

```

**Comment by vinodsowdagar** [comment]
Hi @JoostWan ,

Sorry for the late reply. We have successfully reproduced this issue, but we are not sure why this is happening. 
We need to investigate this further to provide a proper solution.

We have created an internal task to fix this issue and we will try to come up with a solution as soon as possible.
Internal reference: PLGMAGTWOS-679

If you have any further questions in the mean time, please let us know.

**Comment by vinodsowdagar** [comment]
Hi @JoostWan ,

We have been working on a new Magento 2 module, because the current one is based on deprecated methods in Magento 2. We couldn't find a reason as to why this issue is happening in the current one. We noticed however, that in our new module this issue is not happening. We suggest taking a look at it: https://github.com/MultiSafepay/magento2

**Comment by JoostWan** [comment]
@Vinod-MultiSafepay Thanks. Will update to the new version (module).
