### ISSUE TITLE
Error 500 from certain orders

### ISSUE THREAD

**Issue by Green-Bananas** [MultiSafepay/Magento2Msp#142]
Hi,

we krijgen op 1 van de 100 orders een error 500 melding (in dashboard MSP) in de callback na een betaling.
Het lijkt er op dat dit gebeurt bij een betaling van een mixed order van configureerbare en simpele producten. 

Dit lijkt exact hetzelfde: https://github.com/magento/magento2/issues/21663#issuecomment-604381865

Magento ver. 2.3.4

**Comment by Green-Bananas** [comment]
vaneycksport.com:80 185.99.129.21, 162.158.233.36 77.241.90.135 - - [18/Nov/2020:12:00:15 +0100] "GET /nl/multisafepay/connect/notification?transactionid=E5000009855&timestamp=1605697215 HTTP/1.1" 500 501 "-" "Mozilla/5.0 (X11; Debian; Linux x86_64; rv:33.0) Gecko/20100101\")"
vaneycksport.com:80 185.99.129.21, 162.158.233.20 77.241.90.135 - - [18/Nov/2020:12:00:16 +0100] "GET /nl/multisafepay/connect/notification?transactionid=E5000009855&timestamp=1605697216 HTTP/1.1" 500 501 "-" "Mozilla/5.0 (X11; Debian; Linux x86_64; rv:33.0) Gecko/20100101\")"
vaneycksport.com:80 185.99.129.21, 162.158.233.34 77.241.90.135 - - [18/Nov/2020:12:26:02 +0100] "GET /nl/multisafepay/connect/notification?transactionid=E5000009867&timestamp=1605698762 HTTP/1.1" 500 480 "-" "Mozilla/5.0 (X11; Debian; Linux x86_64; rv:33.0) Gecko/20100101\")"
vaneycksport.com:80 185.99.130.21, 162.158.233.34 77.241.90.135 - - [18/Nov/2020:12:41:07 +0100] "GET /nl/multisafepay/connect/notification?transactionid=E5000009867&timestamp=1605699667 HTTP/1.1" 500 480 "-" "Mozilla/5.0 (X11; Debian; Linux x86_64; rv:33.0) Gecko/20100101\")"
vaneycksport.com:80 185.99.130.21, 162.158.233.34 77.241.90.135 - - [18/Nov/2020:12:56:10 +0100] "GET /nl/multisafepay/connect/notification?transactionid=E5000009867&timestamp=1605700570 HTTP/1.1" 500 480 "-" "Mozilla/5.0 (X11; Debian; Linux x86_64; rv:33.0) Gecko/20100101\")"
vaneycksport.com:80 185.99.130.21, 162.158.233.42 77.241.90.135 - - [18/Nov/2020:14:44:47 +0100] "GET /nl/multisafepay/connect/notification?transactionid=E5000006744&timestamp=1605707087 HTTP/1.1" 500 1410 "-" "Mozilla/5.0 (X11; Debian; Linux x86_64; rv:33.0) Gecko/20100101\")"
vaneycksport.com:80 185.99.129.21, 162.158.233.44 77.241.90.135 - - [18/Nov/2020:14:45:35 +0100] "GET /nl/multisafepay/connect/notification?transactionid=E5000004667&timestamp=1605707135 HTTP/1.1" 500 1410 "-" "Mozilla/5.0 (X11; Debian; Linux x86_64; rv:33.0) Gecko/20100101\")"
vaneycksport.com:80 185.99.130.21, 162.158.233.48 77.241.90.135 - - [18/Nov/2020:14:46:43 +0100] "GET /nl/multisafepay/connect/notification?transactionid=E5000007624&timestamp=1605707203 HTTP/1.1" 500 1410 "-" "Mozilla/5.0 (X11; Debian; Linux x86_64; rv:33.0) Gecko/20100101\")"
vaneycksport.com:80 185.99.130.21, 162.158.233.46 77.241.90.135 - - [18/Nov/2020:14:46:44 +0100] "GET /nl/multisafepay/connect/notification?transactionid=E5000007624&timestamp=1605707204 HTTP/1.1" 500 1410 "-" "Mozilla/5.0 (X11; Debian; Linux x86_64; rv:33.0) Gecko/20100101\")"
vaneycksport.com:80 185.99.129.21, 162.158.233.30 77.241.90.135 - - [18/Nov/2020:14:48:31 +0100] "GET /nl/multisafepay/connect/notification?transactionid=E5000009913&timestamp=1605707311 HTTP/1.1" 500 1410 "-" "Mozilla/5.0 (X11; Debian; Linux x86_64; rv:33.0) Gecko/20100101\")"
vaneycksport.com:80 185.99.129.21, 162.158.233.18 77.241.90.135 - - [18/Nov/2020:14:48:38 +0100] "GET /nl/multisafepay/connect/notification?transactionid=E5000009913&timestamp=1605707317 HTTP/1.1" 500 1410 "-" "Mozilla/5.0 (X11; Debian; Linux x86_64; rv:33.0) Gecko/20100101\")"
vaneycksport.com:80 185.99.130.21, 162.158.233.38 77.241.90.135 - - [18/Nov/2020:15:30:47 +0100] "GET /nl/multisafepay/connect/notification?transactionid=E5000009985&timestamp=1605709847 HTTP/1.1" 500 473 "-" "Mozilla/5.0 (X11; Debian; Linux x86_64; rv:33.0) Gecko/20100101\")"
vaneycksport.com:80 185.99.129.21, 162.158.233.48 77.241.90.135 - - [18/Nov/2020:16:01:41 +0100] "GET /nl/multisafepay/connect/notification?transactionid=E5000009985&timestamp=1605711701 HTTP/1.1" 500 473 "-" "Mozilla/5.0 (X11; Debian; Linux x86_64; rv:33.0) Gecko/20100101\")"
vaneycksport.com:80 185.99.129.21, 162.158.233.38 77.241.90.135 - - [18/Nov/2020:16:01:42 +0100] "GET /nl/multisafepay/connect/notification?transactionid=E5000009985&timestamp=1605711702 HTTP/1.1" 500 473 "-" "Mozilla/5.0 (X11; Debian; Linux x86_64; rv:33.0) Gecko/20100101\")"


[Wed Nov 18 15:30:49.130577 2020] [proxy_fcgi:error] [pid 116469:tid 140498161358592] [client 77.241.90.135:61896] AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to undefined method Magento\\Catalog\\Model\\Product\\Type\\Simple\\Interceptor::getConfigurableAttributeCollection() in /var/www/vaneycksport.com/vendor/magento/module-configurable-product/Helper/Product/Options/Loader.php:52\nStack trace:\n#0 /var/www/vaneycksport.com/generated/code/Magento/ConfigurableProduct/Helper/Product/Options/Loader/Interceptor.php(24): Magento\\ConfigurableProduct\\Helper\\Product\\Options\\Loader->load(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#1 /var/www/vaneycksport.com/vendor/magento/module-configurable-product/Model/Product/ReadHandler.php(48): Magento\\ConfigurableProduct\\Helper\\Product\\Options\\Loader\\Interceptor->load(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#2 /var/www/vaneycksport.com/vendor/magento/framework/EntityManager/Operation/Read/ReadExtensions.php(48): Magento\\ConfigurableProduct\\Model\\Product\\ReadHandler->execute(Object(Magento\\Catalog\\Model\\Product\\Interceptor), Array)\n#3 /var/www/vaneycksport.c...'
[Wed Nov 18 16:01:42.024636 2020] [proxy_fcgi:error] [pid 65432:tid 140498496870144] [client 77.241.90.135:14236] AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to undefined method Magento\\Catalog\\Model\\Product\\Type\\Simple\\Interceptor::getConfigurableAttributeCollection() in /var/www/vaneycksport.com/vendor/magento/module-configurable-product/Helper/Product/Options/Loader.php:52\nStack trace:\n#0 /var/www/vaneycksport.com/generated/code/Magento/ConfigurableProduct/Helper/Product/Options/Loader/Interceptor.php(24): Magento\\ConfigurableProduct\\Helper\\Product\\Options\\Loader->load(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#1 /var/www/vaneycksport.com/vendor/magento/module-configurable-product/Model/Product/ReadHandler.php(48): Magento\\ConfigurableProduct\\Helper\\Product\\Options\\Loader\\Interceptor->load(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#2 /var/www/vaneycksport.com/vendor/magento/framework/EntityManager/Operation/Read/ReadExtensions.php(48): Magento\\ConfigurableProduct\\Model\\Product\\ReadHandler->execute(Object(Magento\\Catalog\\Model\\Product\\Interceptor), Array)\n#3 /var/www/vaneycksport.c...'
[Wed Nov 18 16:02:01.471488 2020] [proxy_fcgi:error] [pid 65432:tid 140498664658688] [client 77.241.90.135:14240] AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to undefined method Magento\\Catalog\\Model\\Product\\Type\\Simple\\Interceptor::getConfigurableAttributeCollection() in /var/www/vaneycksport.com/vendor/magento/module-configurable-product/Helper/Product/Options/Loader.php:52\nStack trace:\n#0 /var/www/vaneycksport.com/generated/code/Magento/ConfigurableProduct/Helper/Product/Options/Loader/Interceptor.php(24): Magento\\ConfigurableProduct\\Helper\\Product\\Options\\Loader->load(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#1 /var/www/vaneycksport.com/vendor/magento/module-configurable-product/Model/Product/ReadHandler.php(48): Magento\\ConfigurableProduct\\Helper\\Product\\Options\\Loader\\Interceptor->load(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#2 /var/www/vaneycksport.com/vendor/magento/framework/EntityManager/Operation/Read/ReadExtensions.php(48): Magento\\ConfigurableProduct\\Model\\Product\\ReadHandler->execute(Object(Magento\\Catalog\\Model\\Product\\Interceptor), Array)\n#3 /var/www/vaneycksport.c...'

**Comment by vinodsowdagar** [comment]
Hi @Green-Bananas ,

Bedankt voor jouw bericht.

Wij kunnen aan de hand van de gegeven informatie niet direct zien wat precies het probleem veroorzaakt. De Github issue die jij mee stuurde had te maken met het feit dat wij op bepaalde plekken de deprecated load() functie gebruikten voor het inladen van bepaalde objecten.

Wij zijn op het moment druk bezig met een nieuwe extensie die gebruik maakt van de huidige standaarden zoals het gebruik van service contracts. Omdat er geen gebruik wordt gemaakt van de Loader, zou deze issue in de nieuwe extensie niet voor moeten komen. 

Wellicht is het een idee om te upgraden naar onze nieuwe extensie. Recentelijk hebben wij een stable release hiervoor uitgebracht: https://github.com/MultiSafepay/magento2

Ik raad aan om de nieuwe extensie eerst uit te proberen op een test omgeving, omdat ook de configuratie is gewijzigd. Meer informatie, waaronder de nieuwe features zijn te vinden op de volgende pagina:
https://docs.multisafepay.com/integrations/plugins/magento2/

Mochten er verder nog vragen zijn dan hoor ik dat uiteraard graag.
