### ISSUE TITLE
Custom fee not being added to the final totals

### ISSUE THREAD

**Issue by SinpietruAdrian** [MultiSafepay/Magento2Msp#145]
The total on the Multisafepay page is incorrect because it does not take into account the additional fees introduced by the 3rd party module even if on the website the totals are calculated and displayed correctly.

In cart:
<img width="340" alt="Screenshot 2021-01-27 at 12 50 07" src="https://user-images.githubusercontent.com/28003438/105981486-cb7d0700-609e-11eb-92a5-c652cb78d016.png">

The totals segments:
<img width="401" alt="Screenshot 2021-01-27 at 12 50 48" src="https://user-images.githubusercontent.com/28003438/105981534-d9cb2300-609e-11eb-9ead-a8f9509ee645.png">

The total as seen on the Multisafepay page:
<img width="882" alt="Screenshot 2021-01-27 at 12 51 33" src="https://user-images.githubusercontent.com/28003438/105981613-f10a1080-609e-11eb-87fd-740545f92b03.png">

After debugging your module I noticed that there is support for custom totals so this is expected to work.

Using multisafepay/magento2msp: 1.14.1 and prince/magento2-extrafeepro 1.0.7.
This was reproduced on a clean Magento 2.3.2 and on a Magento 2.3.6 that cotains multiple modules.

Thank you!

**Comment by vinodsowdagar** [comment]
Hi @SinpietruAdrian ,

Recently we have released a new plugin which brings a lot of improvements with custom totals compared to this one.
The feature should work correctly in the new plugin and we recommend upgrading:
https://github.com/MultiSafepay/magento2

For now i am closing this issue.
If the feature is still not working as expected on the new plugin, please create a new issue there so we can investigate it further.
