### ISSUE TITLE
Shipment Error

### ISSUE THREAD

**Issue by nocturnalfrog** [MultiSafepay/Magento2Msp#146]
Not all function return types are taken into account in:
https://github.com/MultiSafepay/Magento2Msp/blob/9a4af7753859817fdc52cfd3d106453fbcc958db/Model/Observers/Shipment.php#L84-L90
This piece of code assumes that an array is always returned by the `shipOrder` function. 

That is however not the case:
https://github.com/MultiSafepay/Magento2Msp/blob/9a4af7753859817fdc52cfd3d106453fbcc958db/Model/Connect.php#L770-L792
There are two cases present in this function where a boolean `true` is returned.  

If any of these cases are triggered Magento throws a "Trying to access array offset on value of type bool in vendor/multisafepay/magento2msp/Model/Observers/Shipment.php on line 86" and the shipment will fail.

**Comment by Stanislau-MultiSafepay** [comment]
Hi! @nocturnalfrog 

Thank you for reporting this.

Unfortunately, this plugin is deprecated and we are not providing support for it anymore. Please, upgrade to our New Magento 2 plugin.

This issue has not occurred in the new plugin and the new plugin also has tons of other improvements.

I am closing this issue for now. If you have any more comments or questions, feel free to create a new issue in the new plugin repository.
