### ISSUE TITLE
Cancel Translation is not working

### ISSUE THREAD

**Issue by Stevie-Ray** [MultiSafepay/Magento2Msp#147]
`$message = "The transaction was canceled or declined and the order was closed, please try again.";`

Is not being translated because the $reason is added to the sentence:

```
$this->messageManager->addError(
                __(
                    $message . $reason
                )
            );
```

https://github.com/MultiSafepay/Magento2Msp/blob/5f00f0f3768c7aa36d2c8523382a84703ff4db49/Controller/Connect/Cancel.php#L146

**Comment by thompalstra** [comment]
Yeah, it's kinda dumb because they fixed the translation error in `Controller/Fastcheckout/Cancel.php` but not in `Controller/Connect/Cancel.php`

**Comment by Stanislau-MultiSafepay** [comment]
Hi! @Stevie-Ray @thompalstra 

Thank you for reporting this.

Unfortunately, this plugin is deprecated and we are not providing support for it anymore. Please, upgrade to our [New Magento 2 plugin](https://github.com/MultiSafepay/magento2). 

This issue has not occurred in the new plugin and the new plugin also has tons of other improvements.

I am closing this issue for now. If you have any more comments or questions, feel free to create a new issue in the new plugin repository.
