### ISSUE TITLE
Remove Fastcheckout button

### ISSUE THREAD

**Issue by SilvanLaroo** [MultiSafepay/Magento2Msp#16]
Hi,

I disabled the fastcheckout feature, but the button is still added. Could you fix this?

**Comment by JonkRuud** [comment]
@SilvanLaroo  Thanks for reporting, we are verifying on our end as we speak. 
When we can reproduce we wil commit a fix for this one.

**Comment by JonkRuud** [comment]
@SilvanLaroo 

Can you check with the commit from https://github.com/MultiSafepay/Magento2Msp/commit/29e6203142ebedf3589867161c44a4a8062aca1b

Can be that you need to clear your browser cache after this.

**Comment by SilvanLaroo** [comment]
Yes, this does fix the issue. Thank you for the fast response.
