### ISSUE TITLE
Allow shipments for non-MSP orders

### ISSUE THREAD

**Issue by PascalBrouwers** [MultiSafepay/Magento2Msp#17]
Put the following code back in MultiSafepay\Connect\Model\Connect in function shipOrder around line 455

```
        $class = get_class($payment);
        if ($class != 'MultiSafepay\Connect\Model\Connect') {
            return true;
        }
```

Otherwise for banktransfer no shipments can be created

**Comment by JonkRuud** [comment]
Hello @PascalBrouwers,

What exact issues do you currently have without this code? If im correct, it was replaced by other code using the helper to check if the selected method was a MultiSafepay method.

**Comment by PascalBrouwers** [comment]
With version 1.4.1 you can't create shipments for order with banktransfer

**Comment by JonkRuud** [comment]
Oke, we will test on our environment and come back to you about this one.

**Comment by PascalBrouwers** [comment]
Ok, putting that piece of code back fixes it btw.

**Comment by JonkRuud** [comment]
oke im able to reproduce and will update the check.

**Comment by JonkRuud** [comment]
@PascalBrouwers  Just commited an updated check.

**Comment by JonkRuud** [comment]
@PascalBrouwers  can you confirm its working for you so we can close the ticket?

**Comment by PascalBrouwers** [comment]
Looks ok, can't test it at the moment though.

**Comment by JonkRuud** [comment]
@PascalBrouwers  oke thanks. For now I will close this one, if you still have issues after using this patch then feel free to reopen so we can take another look.
