### ISSUE TITLE
Error in backend: Duplicate key-sequence ['extra_phone'] in unique identity-constraint

### ISSUE THREAD

**Issue by PascalBrouwers** [MultiSafepay/Magento2Msp#18]
version 1.4.0

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid XML in file /Users/Pascal/Sites/kingdo2/vendor/multisafepay/magento2msp/etc/adminhtml/system.xml:
Element 'field': Duplicate key-sequence ['extra_phone'] in unique identity-constraint 'uniqueFieldId'.
Line: 3071

**Comment by JonkRuud** [comment]
@PascalBrouwers bedankt voor de melding, deze is verholpen in de develop branche met commit https://github.com/MultiSafepay/Magento2Msp/commit/25cfffc122c04a9c86c41ef6d02cd919f2f17a8a vandaag/morgen zullen wij een nieuwe release vrijgeven waarin deze is verwerkt.

**Comment by JonkRuud** [comment]
@PascalBrouwers  the fix is now added to release 1.4.2
