### ISSUE TITLE
MultiSafepay PHP + Release version

### ISSUE THREAD

**Issue by Echron** [MultiSafepay/Magento2Msp#2]
Hi,

I see that there is a general Multisafepay PHP library ([https://github.com/MultiSafepay/PHP](https://github.com/MultiSafepay/PHP)). Wouldn't it be better to require that one in the Magento module to keep code up to date as possible?

And it would be good to create a tag on the master branch for version 1.1.0 so developers can do
`composer require multisafepay/magento2msp` and get the latest stable version instead of
`composer require multisafepay/magento2msp:dev-master` which will give the latest commit on the master branch.

Greetings,

Stijn

**Comment by JonkRuud** [comment]
Hello Stijn,

Tag 1.1.0 has just been added. About the PHP library, at the moment that became more a stand alone project with all test cases then the API code only so I think for now we will leave it like this and setup a new API core that we can include
