### ISSUE TITLE
Logo fastcheckout visible cart and checkout while being disabled

### ISSUE THREAD

**Issue by PascalBrouwers** [MultiSafepay/Magento2Msp#20]
Version 1.4.0

Logo fastcheckout is visible in cart and checkout while being disabled.

**Comment by JonkRuud** [comment]
@PascalBrouwers  this one is also fixed with de develop branch, commit https://github.com/MultiSafepay/Magento2Msp/commit/29e6203142ebedf3589867161c44a4a8062aca1b and will also be fixed with the release of today/tomorrow

**Comment by JonkRuud** [comment]
@PascalBrouwers  the fix is now added to release 1.4.2
