### ISSUE TITLE
Compilation error on Fastcheckout Button

### ISSUE THREAD

**Issue by rubenelshof** [MultiSafepay/Magento2Msp#22]
When compiling with setup:di:compile i am getting the following error:

Incorrect dependency in class MultiSafepay\Connect\Block\Fastcheckout\Button in /app/code/MultiSafepay/Connect/Block/Fastcheckout/Button.php
\Magento\Framework\View\Asset\Repository already exists in context object
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object

Magento version: 2.1.6
MultiSafepay plugin version: 1.4.2

**Fix that is working for me**
Removing the following lines:
\Magento\Framework\View\Asset\Repository $assetRepo,
\Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig,

Changing these lines:
$this->_assetRepo = $assetRepo;
$this->_scopeConfig = $scopeConfig;

To:
$this->_assetRepo = $context->getAssetRepository();
$this->_scopeConfig = $context->getScopeConfig();

**Comment by JonkRuud** [comment]
Thanks for reporting. We made a mistake and got this fixed already in a local branch but forgot to add it. We will do a release to 1.4.3 today to correct.
