### ISSUE TITLE
No notification for canceled/declined payments

### ISSUE THREAD

**Issue by royvanos** [MultiSafepay/Magento2Msp#24]
Hi Ruud,

We've noticed that users don't get notifications after canceling or declining payments in the test iDeal payment gateway, is this a bug or has this not been implemented yet?

If not implemented, is there a possibility this can be implemented soon? It might result in abandoned carts because customers don't get proper notifications.

Thanks! 
Roy van Os - Active Ants

**Comment by JonkRuud** [comment]
@royvanos  Just to confirm, do you mean an email from magento to the consumer when the order has been cancelled? 

If so, then I will check and come back to you about this one.

**Comment by royvanos** [comment]
@JonkRuud whoops, I forgot to mention context there... I mean after being redirected back to /checkout/cart after canceling/declining the payment in the test gateway. We think it would be alot more clear for customers to see a notication like this after canceling/declining a payment. (see screenshot for example)
![selection_045](https://cloud.githubusercontent.com/assets/5882109/26397218/d70fb376-4075-11e7-9fb8-9440aeb2a105.png)

**Comment by JonkRuud** [comment]
@royvanos  thanks for the screenshot. Will check as this should be in place if im correct.

**Comment by JonkRuud** [comment]
@royvanos  I just added this one, seems we forgot it for these situations.

**Comment by royvanos** [comment]
@JonkRuud Awesome! I'm going to test it right away and will let you know if it works.

**Comment by royvanos** [comment]
@JonkRuud It works! Thanks for the fast commits!
