### ISSUE TITLE
Canceling an order using the test gateway generates an exception

### ISSUE THREAD

**Issue by royvanos** [MultiSafepay/Magento2Msp#25]
Good morning Ruud!

We've found an issue/exception when canceling an order using the MSP test gateway.

The MSP module tries to clear the caches after canceling an order, the exception is thrown in the MultiSafepay\Connect\Controller\Connect\Connect class at line 102. We think it throws an exception because the unlockProcess tries to use the $this->lockFilePath which is null because it hasn't been set using the lockProcess function. We temporarily fixed this by adding $this->_mspHelper->lockProcess('multisafepay-'.$params['transactionid']); after line 69 in MultiSafepay\Connect\Controller\Connect\Connect.

I hope this information is enough to fix this issue!

Roy van Os - Active Ants

**Comment by JonkRuud** [comment]
@royvanos  thanks for reporting, we will look into it.

**Comment by JonkRuud** [comment]
@royvanos do you mind checking if these changes fix your issue.

**Comment by JonkRuud** [comment]
@royvanos  can you confirm if the commit fixed your issue?

**Comment by royvanos** [comment]
Goodmorning Ruud, I didn't test this code yet because we had a pretty busy week, I will do my best to test this code thoroughly next week.

I changed the file myself on our environment and it seems to work well.
