### ISSUE TITLE
Usage of protected attribute instead of getter method

### ISSUE THREAD

**Issue by robbertstevens** [MultiSafepay/Magento2Msp#26]
These line numbers should be fixed:
https://github.com/MultiSafepay/Magento2Msp/blob/master/Model/Connect.php#L255
https://github.com/MultiSafepay/Magento2Msp/blob/master/Model/Connect.php#L258
https://github.com/MultiSafepay/Magento2Msp/blob/master/Model/Connect.php#L269
https://github.com/MultiSafepay/Magento2Msp/blob/master/Model/Connect.php#L276
https://github.com/MultiSafepay/Magento2Msp/blob/master/Model/Connect.php#L462
https://github.com/MultiSafepay/Magento2Msp/blob/master/Model/Connect.php#L465
https://github.com/MultiSafepay/Magento2Msp/blob/master/Model/Connect.php#L481
https://github.com/MultiSafepay/Magento2Msp/blob/master/Model/Connect.php#L499
https://github.com/MultiSafepay/Magento2Msp/blob/master/Model/Connect.php#L695
https://github.com/MultiSafepay/Magento2Msp/blob/master/Model/Connect.php#L698
https://github.com/MultiSafepay/Magento2Msp/blob/master/Model/Connect.php#L769
https://github.com/MultiSafepay/Magento2Msp/blob/master/Model/Connect.php#L909
https://github.com/MultiSafepay/Magento2Msp/blob/master/Model/Connect.php#L918
https://github.com/MultiSafepay/Magento2Msp/blob/master/Model/Connect.php#L921
https://github.com/MultiSafepay/Magento2Msp/blob/master/Model/Connect.php#L1015
https://github.com/MultiSafepay/Magento2Msp/blob/master/Model/Connect.php#L1018

The `->_code` should be `->getCode()` because you cannot access a protected attribute obviously :)

**Comment by JonkRuud** [comment]
@robbertstevens  thanks for reporting, we will look into this one for the next release
