### ISSUE TITLE
No CHANGELOG.md

### ISSUE THREAD

**Issue by Hexmage** [MultiSafepay/Magento2Msp#27]
It would be nice for the module to have a changelog, it becomes tiring to read through commit messages after a while.

**Comment by Jasper-MultiSafepay** [comment]
Hi Hexmage,

Thank you for your suggestion, this is something we are indeed planning to add.
We will add this, and this would also be available in our releases list.
Once we have added this, we will let you know by closing this issue.

**Comment by JonkRuud** [comment]
Hi @Hexmage the changelog.md is now part of the release
