### ISSUE TITLE
[Critical] When cancelling order on payment provider page, the entire var folder is being cleared

### ISSUE THREAD

**Issue by koenner01** [MultiSafepay/Magento2Msp#29]
If you cancel your order on the msp payment page, the entire var folder is being cleared (!?) upon redirect and everything in it will be rebuild while returning to the checkout/cart

This is not only a ridiculous bug (how and why would you even do this!!), but it breaks about everything on the webshop upon arrival if you were logged in (because the sessions are being stored inside the var folder...)

**Prereq**
- Magento CE 2.1/6
- MSP 1.4.3
- PHP 7.0

**Comment by Jasper-MultiSafepay** [comment]
I have now reproduced this bug. We will investigate the exact cause for this and will keep you updated.

**Comment by Jasper-MultiSafepay** [comment]
I have tested and added a commit at jasper-multisafepay/Magento2Msp@283d2bd01ef5463a34b5a3f2f3707433da791ae0 which should solve this issue.

**Comment by koenner01** [comment]
I can confirm that the fix works!
