### ISSUE TITLE
404's on payment images

### ISSUE THREAD

**Issue by Tjitse-E** [MultiSafepay/Magento2Msp#30]
![commander-1](https://user-images.githubusercontent.com/14849044/27291445-83172f4c-5510-11e7-8638-9c8af90518b4.png)

On certain locales (fr_BE, de_AT, etc.) the payment images don't work. This is because the locale is used in the image url. The problem occurs on version 1.4.3.

**Comment by Jasper-MultiSafepay** [comment]
Thanks for reporting and the commit.
I'll discuss this with the Magento2 plugin developer to see if we can merge this.

**Comment by Tjitse-E** [comment]
@JonkRuud is this issue fixed in the latest release?

**Comment by JonkRuud** [comment]
@Tjitse-E  we didn't revert back as images need to be shown by locale as they can be different. Within the next release we improved this so there will be a fallback
