### ISSUE TITLE
Column payment status in order screen 

### ISSUE THREAD

**Issue by GuidoHub** [MultiSafepay/Magento2Msp#40]
I would like to have an extra column which shows the status of the payment. No I have to open the order to see if the payment went well. We get a lot of declined orders so it would be nice to have a quick overview of which orders can be ignored.

**Comment by Jasper-MultiSafepay** [comment]
We could be wrong, but this is already available as the column "status"?
This can be enabled in the columns.
![image](https://user-images.githubusercontent.com/26003384/29778867-174968f6-8c11-11e7-85ff-b24825dfde1f.png)

**Comment by GuidoHub** [comment]
I have it activated the column and I see status "Processing" but would expect status "completed" for the payment. I think the status is an overal status for the order itself and not specially for the payment. 

This is the last notification I got on my test order:

Aug 26, 2017 3:15:14 AM Processing Customer Not Notified
MultiSafepay status: completed
Notificatie ontvangen: Betaling vastgelegd voor € 349,00. Transactie-ID: "2762004"

As you can see, the payment is completed.

**Comment by Jasper-MultiSafepay** [comment]
@GuidoHub Could you send an email to techsupport@multisafepay.com?
So we can continue this through our support system.
