### ISSUE TITLE
Fatal error when create a shipping

### ISSUE THREAD

**Issue by magefan** [MultiSafepay/Magento2Msp#42]
We have detected an issue during shipping creation (Magento 2.1.9), when order has no sales transactions attached to it then we get an error:

```
<b>Fatal error</b>:  Uncaught Error: Call to a member function getAdditionalInformation() on boolean in app/code/MultiSafepay/Connect/Model/Connect.php:463
Stack trace:
#0 app/code/MultiSafepay/Connect/Model/Observers/Shipment.php(66): MultiSafepay\Connect\Model\Connect-&gt;shipOrder(Object(Magento\Sales\Model\Order))
#1 vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): MultiSafepay\Connect\Model\Observers\Shipment-&gt;execute(Object(Magento\Framework\Event\Observer))
#2 vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault-&gt;_callObserverMethod(Object(MultiSafepay\Connect\Model\Observers\Shipment), Object(Magento\Framework\Event\Observer))
#3 vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault-&gt;dispatch(Array, Object(Magento\Framework\Event\Observer))
#4  in <b>app/code/MultiSafepay/Connect/Model/Connect.php</b> on line <b>463</b><br>
```

We've made a temporary quick fix in app/code/MultiSafepay/Connect/Model/Connect.php line 463
code
`$transaction_details = $transaction->getAdditionalInformation(\Magento\Sales\Model\Order\Payment\Transaction::RAW_DETAILS);`
was replaces with
`$transaction_details = $transaction ? $transaction->getAdditionalInformation(\Magento\Sales\Model\Order\Payment\Transaction::RAW_DETAILS) : [];`

but maybe you have a better solution.
Could you please fix this issue (or confirm that our fix is good) and include a fix to the next release?

Best regards.

**Comment by Jasper-MultiSafepay** [comment]
@magefan 
When there isn't a transaction, then the transaction hasn't been made at MultiSafepay.
Your fix will still send the shippment request to MSP.
I propose the following fix which will also be included in next release

> $transaction = $transactionRepository->getByTransactionId($transaction_id, $payment->getId(),$order->getId());
if ($transaction == NULL) {
    return true;
}       
$transaction_details = $transaction->getAdditionalInformation(\Magento\Sales\Model\Order\Payment\Transaction::RAW_DETAILS);

**Comment by magefan** [comment]
Thanks.
