### ISSUE TITLE
Shopping cart is restored after payment with 'Banktransfer'

### ISSUE THREAD

**Issue by Tantuss** [MultiSafepay/Magento2Msp#45]
See basically for the description the issue:
https://github.com/MultiSafepay/Magento2Msp/issues/41

The only difference that it is solved for the payment methods which are not from MSP.
It is not solved for payment methods which have a gateway of MSP and do not get another status then 'New' when the order is finished (for example, Banktransfer).

**Comment by Jasper-MultiSafepay** [comment]
@Tantuss 
I will create an internal ticket for this and keep you updated.

**Comment by royvanos** [comment]
@jasper-multisafepay is it possible that you guys can make this configurable so we can disable this if we want to? We've had countless customers actually ordering twice, it's their fault that they do this, but it would be generally better if this wouldn't happen in the first place by disabling it.

For now I've just removed the 'msp_action_predispatch_checkout_cart_index' observer from the frontend/events.xml file.

**Comment by JonkRuud** [comment]
@Tantuss  @royvanos  The current develop branch has a fix for this and will be included within the next release this week.

**Comment by JonkRuud** [comment]
@Tantuss  @royvanos  release 1.4.7 is now online on github and includes the fix for this issue, so, we will close this ticket.
