### ISSUE TITLE
Error 1027 when using discount coupon and payment method "Betaal na ontvangst"

### ISSUE THREAD

**Issue by GuidoHub** [MultiSafepay/Magento2Msp#48]
The user will get an Error: "1027 - Totaalbedrag van de winkelwagen moet gelijk zijn aan het bedrag van de transactie." When he uses a discount coupon in combination with payment method "Betaal na ontvangst".

**Comment by JonkRuud** [comment]
@GuidoHub  thanks for reporting, we will test and look into this one. Just to verify, your using 1.4.6 at the moment?

**Comment by GuidoHub** [comment]
No, not using 1.4.6 at the moment but verified that the issue is also in 1.4.6. It's a known issue for almost 2 weeks now but still waiting for a response from your side. Something to do with tax settings.

**Comment by JonkRuud** [comment]
@GuidoHub  I have check on our end, a ticket is registered about this issue internally and is pending for the next 1.4.7 release, we expect to release this by end next week.

**Comment by GuidoHub** [comment]
@JonkRuud, still no release. I am waiting for more then 3 weeks now and I still can't give my customers a solution.

**Comment by JonkRuud** [comment]
@GuidoHub  we are working on this but it takes time to develop, review code and test in multiple environments and configurations.

**Comment by GuidoHub** [comment]
@JonkRuud I understand but for now my visitors are getting an error which I cannot block and it will terminate the order. Also the product is set out of stock after that so they cannot order it again with another payment.

**Comment by GuidoHub** [comment]
@JonkRuud, can you update this ticket #VUC-751-99449 so I will be updated and your college's will know about the issue?

**Comment by JonkRuud** [comment]
@GuidoHub  I assigned the ticket to the developer who is working on this issue.

**Comment by GuidoHub** [comment]
@JonkRuud Still waiting for a fix. It has been more then a month now.

**Comment by Jasper-MultiSafepay** [comment]
@GuidoHub 
A week ago in our internal ticket VUC-751-99449 we have send you a test version of our plugin.
But we haven't received a response yet from you if this has solved your issue.
Could you please reply on the aforementioned ticket?

**Comment by GuidoHub** [comment]
@jasper-multisafepay Didn't received an email with attachment. Also send a reply on the ticket yesterday but didn't get any response yet.

**Comment by Jasper-MultiSafepay** [comment]
@GuidoHub 
Weird, I have send another reply to the main email and your gmail.
I have just send you another test email through my private mail.
Could you check if you have received that one in your gmail?

**Comment by Jasper-MultiSafepay** [comment]
@GuidoHub 
Seems to be an attachment filtering issue.
I have contacted you again through the ticket.
Could you please respond on the ticket VUC-751-99449

**Comment by JonkRuud** [comment]
@GuidoHub  the new release is now added to Github so we will close this issue.
