### ISSUE TITLE
Wrong installation package update 1.4.6

### ISSUE THREAD

**Issue by GuidoHub** [MultiSafepay/Magento2Msp#49]
The update package for update 1.4.6 only contains folder "Magento2Msp" with all files. I would expect to see the same folders as in update 1.4.5 and before. "app\code\MultiSafepay\Connect\*.*"

**Comment by JonkRuud** [comment]
@GuidoHub  do you mean the packages from github when using, or the manual download on the MultiSafepay website?

**Comment by GuidoHub** [comment]
It's the manual download on the website.

**Comment by JonkRuud** [comment]
@GuidoHub  we will upload 1.4.7 to our website with correct path so we will close this one.
