### ISSUE TITLE
Only use `$shipping` if not empty

### ISSUE THREAD

**Issue by jissereitsma** [MultiSafepay/Magento2Msp#50]
In the `Connect` class line 333 (https://github.com/MultiSafepay/Magento2Msp/blob/master/Model/Connect.php#L333) a reference to `$shipping->getStreetLine()` is made. However, when a product is not a Simple Product but a Virtual Product, shipping is not involved and hence `$shipping` is empty. There should be a `if` check if `$shipping` is empty.

**Comment by jissereitsma** [comment]
Reference https://github.com/MultiSafepay/Magento2Msp/pull/51

**Comment by JonkRuud** [comment]
@jissereitsma  thanks for reporting, we already had this one fixed internally and will push this to Github probably tomorrow/beginning next week.

**Comment by JonkRuud** [comment]
@jissereitsma  slight delay in pushing, but the current dev version has a fix for this one, so will close this issue.

**Comment by jissereitsma** [comment]
Cool. thanks for the update!
