### ISSUE TITLE
[PLGMAGTWOS-498] Uncaught typeError on multiple property when fastcheckout enabled

### ISSUE THREAD

**Issue by GuidoHub** [MultiSafepay/Magento2Msp#52]
When you have enabled fastcheckout you will get several uncaught typeErrors when adding a product to the cart.

- Uncaught TypeError: Cannot read property 'quoteData' of undefined
- Uncaught TypeError: Cannot read property 'defaultSuccessPageUrl' of undefined
- Uncaught TypeError: Cannot read property 'storeCode' of undefined
- Uncaught TypeError: Cannot read property 'checkoutAgreements' of undefined
- Uncaught TypeError: Cannot convert undefined or null to object

Tested with chrome in incognito mode.

Steps to reproduce: 

- Enable fastcheckout in Stores->Configuration->Multisafepay (1.4.6) ->Fastcheckout
- Go to product detail page
- Add product to cart
- You will now see the script errors.

**Comment by Jasper-MultiSafepay** [comment]
A patch with this fix can be found in a2b69b9dd5adf9a0592efdecff70e2a447651d06
We will include this patch in the upcoming version of our plugin.
