### ISSUE TITLE
Cart and Checkout page nginx eror!

### ISSUE THREAD

**Issue by lery12** [MultiSafepay/Magento2Msp#54]
Hi,

Yesterday we got a weird problem where the shopping cart and checkout page are not able to load.
I looked into the logs and saw this: [2017-11-23 22:32:15] main.CRITICAL: Error Unable to communicatie with the MultiSafepay payment server (28): Connection timed out after 120001 milliseconds. [] []

The test environment was also offline for a couple of hours.
But the problem is that the shop is unable to load (got a 502 Bad Gateway) the shopping cart of checkout page when Mutlisafepay server is down...

**Comment by JonkRuud** [comment]
@lery12  thanks for reporting, we will check this and fix in the next release.

**Comment by lery12** [comment]
The release that will be coming out next week? Or the release after that?

**Comment by JonkRuud** [comment]
@lery12 it will be in the next release. We will try to get it to the devel branch today for an official release next week.
