### ISSUE TITLE
[XXL-489-12859] JS error with Ideal

### ISSUE THREAD

**Issue by lery12** [MultiSafepay/Magento2Msp#56]
Hi, 

I updateded to version 1.4.7 and now i cant pay with Ideal anymore.
Other methodes work.
I get this error:
`default.js:101 Uncaught TypeError: Cannot read property 'placeOrder' of null`

**Comment by Jasper-MultiSafepay** [comment]
@lery12 
Could you send an email to techsupport@multisafepay.com with your accountID so we can investigate this?

**Comment by lery12** [comment]
done, thanks for the fast response!
