### ISSUE TITLE
Feature request: possibility to send a payment link to customer for pending order in order view page

### ISSUE THREAD

**Issue by GuidoHub** [MultiSafepay/Magento2Msp#57]
I would like to have an option in order view page to send a payment link to the customer for a pending order. Would be nice if you could also create an email template for this so we could set the text that needs to be send.

We know there is an option "SecondChance" in your backend but this email is send after a few hours.

**Comment by JonkRuud** [comment]
As this request was moved internally to our backlog the request will be closed here. Internal reference task PLGMAGTWOS-333
