### ISSUE TITLE
Fixed Product Tax not in payment

### ISSUE THREAD

**Issue by Echron** [MultiSafepay/Magento2Msp#58]
When i checkout a product with an Fixed Product Tax then the extra tax is not visible and calculated on the MultiSafepay payment page.

My products are inputted with price incl. in Magento (It's a B2C shop and price roundings were an issue if we input prices excl vat).

When i check the multisafepay.log file is see that this product is send to the API with a "unit_price" that's excluding taxes, there is a property to say that it has to be 21% VAT but no property to add the FPT tax.

I also don't see any indication in the code to add FPT taxes. I see a lot of "fixes" and price calculations.
Maybe something is wrong because i input the prices incl VAT...

**Comment by Echron** [comment]
I just checked with another client where the prices are put in excl VAT and it's the same issue :
![multisafepay_fpt](https://user-images.githubusercontent.com/2070180/33884946-f995758c-df41-11e7-9e4b-ed9fa80acf8a.png)

**Comment by JonkRuud** [comment]
@Echron  thanks for reporting, we will check on our end and work on a solution. Might be this is indeed not yet processed.

**Comment by Echron** [comment]
@JonkRuud Do you have any news? This is a blocking issue for one of our projects which have to go live before the end of the year. If you have any quick fix i could apply it would be welcome

**Comment by JonkRuud** [comment]
@Echron unfortunately we don't have a quick fix yet. We are working on this one in our current sprint for the next release, and should be released the first week of 2018 at latest.

**Comment by JonkRuud** [comment]
@Echron we just released version 1.4.8 that implemented FPT support
