### ISSUE TITLE
Fatal error RestoreQuote

### ISSUE THREAD

**Issue by rikwillems** [MultiSafepay/Magento2Msp#60]
After the last update to 1.4.8 I get the following error. Disabling the Keep cart alive feature doesn't help.

Fatal error: Uncaught Error: Call to a member function getMethodInstance() on null in vendor/multisafepay/magento2msp/Model/Observers/RestoreQuote.php on line 6

**Comment by Jasper-MultiSafepay** [comment]
@rikwillems 
This part of the code was already in place since 1.4.6 and could be caused by the session not being available.
Could you send an email to techsupport@multisafepay.com ?
We would like to investigate this further.

**Comment by rikwillems** [comment]
When I replace the 1.4.8 code with the 1.4.7 code in the execute method of the RestoreQuote observer it works again. The added code does make a incompatible change.

**Comment by Jasper-MultiSafepay** [comment]
Unfortunately we cannot reproduce this on our test environments.
Would it be possible if we investigate this further on your environment?
If so, could you send an email to techsupport@multisafepay.com ?

**Comment by rikwillems** [comment]
After accidentally updating the module again my problem is back. Can you please review this code change?

**Comment by Jasper-MultiSafepay** [comment]
We have done our code reviews and testing and cannot find any issues.
Would it be possible if we investigate this further on your staging environment?
If so, could you send an email to techsupport@multisafepay.com ?

**Comment by rikwillems** [comment]
Thank you Jasper, I've sent you an email.

**Comment by Jasper-MultiSafepay** [comment]
Should be solved with 1.4.9
