### ISSUE TITLE
Not correct file structure of the package 1.4.8

### ISSUE THREAD

**Issue by melnickforever** [MultiSafepay/Magento2Msp#61]
Not correct file structure of the package 1.4.8
Can you please review file structure of package 1.4.8 from page https://www.multisafepay.com/solutions/shop-plug-ins/detail/plugins/magento-2-1/
As i see all module removed from "connect" folder but we have old namespaces 
Example namespace MultiSafepay\Connect\Model

**Comment by JonkRuud** [comment]
Hello @melnickforever  thanks for reporting, we noticed the issue and will be uploading a new package

**Comment by JonkRuud** [comment]
@melnickforever  the package is now update on our website.

**Comment by melnickforever** [comment]
Thank you for a quick response.
