### ISSUE TITLE
[PLGMAGTWOS-231] Could not refund order with shipping

### ISSUE THREAD

**Issue by bartlubbersen** [MultiSafepay/Magento2Msp#63]
If I try to refund an order with shipping costs online I get the following error: "Error: Refund not processed online as it did not match the complete shipping cost.". Even though the shipping amount is fully credited. After some code checking I found out that in Model/Connector you are checking the shipping_amount filled in the credit memo form against the shipping_amount in the order.

In our case the data in the creditmemo was filled (by default) including tax, while the shipping_amount was excluding tax. After I changed the order field from shipping_amount to shipping_incl_tax the problem was solved for us. However this might not work with other configurations.

**Comment by Jasper-MultiSafepay** [comment]
Correct, we have received the same notice a week ago.
This is something that is being resolved with the next version 1.4.9
Instead of getShippingAmount we should check getShippingInclTax depending on the tax setting within the store.
Your workaround/solution is workable for now.

**Comment by Jasper-MultiSafepay** [comment]
Fixed in 1.6.2
