### ISSUE TITLE
Please add a replace tag in the composer.json because of the renaming

### ISSUE THREAD

**Issue by PascalBrouwers** [MultiSafepay/Magento2Msp#7]
Please add a replace tag in the composer.json because you renamed it from multisafepay/connect to multisafepay/magento2msp

For an example see: https://github.com/php-amqplib/php-amqplib/blob/master/composer.json

**Comment by Echron** [comment]
This package was never named or registered as multisafepay/connect. This is the Magento2 Multisafepay module.

**Comment by PascalBrouwers** [comment]
Ah you are correct my bad, it's the fork we are using that is incorrect.
