### ISSUE TITLE
[PLGMAGTWOS-335] Long load time cart page because of MSP

### ISSUE THREAD

**Issue by Tantuss** [MultiSafepay/Magento2Msp#70]
Last Tuesday 19-6-2018 I noticed that during evening / night the load time of adding an product to my shopping basket took 90 seconds or even more to load.

After disabling the MSP extension, the load time was 2 seconds.

After some short checking I found that the MSP extension is holding up the load of the cart page, because it is communicating to the MSP servers and they do not react fast enough.

Why is this actually at all needed? 
The cart page is not a checkout page, so why does MSP need to be contacted?

And can I disable this un-wanted behaviour?
And / or can this call being done async so that my clients do not need to wait longer because of slow reaction from MSP servers?

**Comment by JonkRuud** [comment]
@Tantuss Our apologies for not receiving an answer on this one on github. We have missed this one unfortunately. Strange that is was slow at that time, I have checked on our end and didn't find a reason for this. For what I can think, the only call that might be done is requesting the Issuers list for Ideal, but we must check to be sure. Internally I have created a task for this. Internal reference PLGMAGTWOS-335

**Comment by vinodsowdagar** [comment]
@Tantuss ,

Thank you for the report.

Unfortunately, this plugin is deprecated and we are not providing support for it anymore. 
Please upgrade to our [New Magento 2 plugin.](https://github.com/MultiSafepay/magento2).

This issue has not occurred in the new plugin and the new plugin also has tons of other improvements.
I am closing this issue for now. 
If you have any more comments or questions, feel free to create a new issue in the new plugin repo.
