### ISSUE TITLE
Double invoice + orders on processing instead of complete

### ISSUE THREAD

**Issue by Esteraa** [MultiSafepay/Magento2Msp#72]
We are running on M2.2.4 with the MSP version 1.5.0.

Sometimes orders get a double invoice. When this happens, the order status of these orders keep staying on "processing" instead of "complete". 

Can you investigate this issue?

**Comment by Jasper-MultiSafepay** [comment]
Will do, issue is picked up for investigation through our ticket system.

**Comment by Esteraa** [comment]
The issue is fixed with PR #77
