### ISSUE TITLE
Table 'sales_order_grid' not updated

### ISSUE THREAD

**Issue by GuidoHub** [MultiSafepay/Magento2Msp#74]
You have an update script that needs to add column 'multisafepay_status' to table 'sales_order_grid' but this isn't working in my enviroment, Magento 2.1.14 and I am using **table prefix**.

I also see that you are using file UpgradeData.php but I would expect upgradeSchema.php for adding the column and upgradeData for adding the new attribute.

**Comment by Jasper-MultiSafepay** [comment]
Thanks for reporting this.
Will be looked at and included in the current sprint.
I'll check if we can include the table prefix solution asap

**Comment by juho-jaakkola** [comment]
I have this same problem. My tables are not using a prefix. My first suspicion was the the upgrade script is not compatible with [split database](https://devdocs.magento.com/guides/v2.2/config-guide/multi-master/multi-master.html).

@GuidoHub Is your site using single database or a split one?

**Comment by GuidoHub** [comment]
@juho-jaakkola I am using a single database. But I think it's because the update statement is not in script file upgradeSchema.php but in file upgradeData.php

**Comment by Jasper-MultiSafepay** [comment]
We released 1.6.0 which solves this issue.
