### ISSUE TITLE
Double invoice + orders on "pending payment" instead of "processing"

### ISSUE THREAD

**Issue by Esteraa** [MultiSafepay/Magento2Msp#76]
We are running on M2.2.6 with the MSP version 1.6.0.

All orders get a double invoice. When this happens, the order status of these orders keep staying on "pending payment" instead of "processing". We can see that the orders are already paid, so the order status should change.

Can you investigate this issue?

**Comment by kaybeudeker** [comment]
@EsteraVendic  May i ask what option you have selected under "**When send the order confirmation e-mail**"? Over here, with "_After transaction paid_" selected (CE 2.2.6 + MSP 1.6.0), the invoice doesn't get generated and/or send at all..

**Comment by Esteraa** [comment]
@kaybeudeker As you can see, we selected "After transaction", but we get the invoice 2 times per order. 
![msp](https://user-images.githubusercontent.com/30499229/46407460-50de8f80-c70f-11e8-88ce-1d7f5dccc824.png)

**Comment by kaybeudeker** [comment]
Well.. don't know what happened but since yesterday the invoice -just 1- gets generated and send but now the status -default M2 (order)status and Multisafepay status- changes into 'complete' instead of 'processing' while the order doesn't contain a shipment yet.

**Comment by Jasper-MultiSafepay** [comment]
This specific issue should be resolved with the 1.6.1 release
@kaybeudeker 
If you are still having different issues, could you create a new issue (here or by contacting our Support)

**Comment by kaybeudeker** [comment]
Latest available version is still 1.6.0 @ https://packagist.org/packages/multisafepay/magento2msp Please update

**Comment by JonkRuud** [comment]
Hello @kaybeudeker the package on packagist has just been updated, it should be available now.
