### ISSUE TITLE
Feature request: allow developers to add/manipulate specific data which is being send to MSP

### ISSUE THREAD

**Issue by hostep** [MultiSafepay/Magento2Msp#8]
Hi guys

We have a certain client which asks us to send a custom ID they use in their own system to MSP.
But I have a hard time implementing this without rewriting your code.

I was trying to change the [description](https://github.com/MultiSafepay/Magento2Msp/blob/6ff332c/Model/Connect.php#L328) which gets send to MSP, by using a [Plugin](http://devdocs.magento.com/guides/v2.1/extension-dev-guide/plugins.html) or even a [Preference](http://devdocs.magento.com/guides/v2.1/extension-dev-guide/build/di-xml-file.html#abstraction-implementation-mappings) on the `MultiSafepay\Connect\Model\Api\Objects\Orders::post` method.
But unfortunately I can't get this working, since that `Orders` class is just [instantiated using `new`](https://github.com/MultiSafepay/Magento2Msp/blob/427b003/Model/Api/MspClient.php#L54) instead of being injected using DI.

So one option to allow us developers to manipulate this data would be to inject that `Orders` class using DI which would allow us to manipulate how it works.
Or another - and maybe better way - would be if you dispatch a custom event just before that big array of data gets send to MSP, so we can manipulate this data using an [Observer](http://devdocs.magento.com/guides/v2.1/extension-dev-guide/events-and-observers.html)

Is this something you would be interested in?

I can create a PR for this if this should interest you?

Thanks!

**Comment by JonkRuud** [comment]
Hello Hostep,

If you can create a PR (for the devel branch) for it then we can look into it and also test with it.

**Comment by hostep** [comment]
@JonkRuud: has this been added? I can't see anything related to this in the develop branch?

If not: can you reopen, because we still need this. I still plan on submitting a PR for this, but haven't found the time yet. It might take me a couple more weeks though ...
But if anyone else feels like it, go ahead! :)

**Comment by JonkRuud** [comment]
@hostep  Not yet, I closed this one as we didn't get any reply. I will reopen.

**Comment by JonkRuud** [comment]
As this feature request was also created internally for our backlog we will close this one. For reference, Internal request is PLGMAGTWOS-332
