### ISSUE TITLE
Msp 1.6.1 Internet Explorer not working 

### ISSUE THREAD

**Issue by tukker01** [MultiSafepay/Magento2Msp#80]
When using Internet Explorer  Msp is not working de pay methods are not showing, see screenshot also the spinner is loading and loading. Chrome and Firefox everything are working fine.
In 1.4.9 it was stil working after upgrading to 1.6.1 its stuck

![2018-10-18 20_17_00-217 100 217 14 - remote desktop connection](https://user-images.githubusercontent.com/25117860/47175353-31e91b80-d313-11e8-9ae6-5444704cf731.png)

**Comment by Jasper-MultiSafepay** [comment]
@tukker01 
This is fixed with https://github.com/MultiSafepay/Magento2Msp/pull/79
This will be included in the next version of the plugin.
Can you use the resolution from https://github.com/MultiSafepay/Magento2Msp/pull/79/commits/58b7eee9d4106a0fb770edf768fa29c85c9e910e ?

**Comment by tukker01** [comment]
I have tried to modify the files connect-method.js but unfortunately it does not work for us

**Comment by Jasper-MultiSafepay** [comment]
- Did you redeploy the static content?
- Did you clear the browser cache?

**Comment by tukker01** [comment]
Yes I did

**Comment by Jasper-MultiSafepay** [comment]
In that case could you send an email to techsupport@multisafepay.com with your account details, so we could research this further?

**Comment by tukker01** [comment]
See your email

**Comment by kaybeudeker** [comment]
On production/live server, run the command `bin/magento deploy:mode:set production`, just redeploying the static-content and clearing the cache doesn't work indeed, this did..

**Comment by Jasper-MultiSafepay** [comment]
Was indeed a caching problem.
Solved in current release [1.6.2](https://github.com/MultiSafepay/Magento2Msp/releases/tag/1.6.2)
