### ISSUE TITLE
[PLGMAGTWOS-355] Instant purchase integration

### ISSUE THREAD

**Issue by Darkbelg** [MultiSafepay/Magento2Msp#86]
Are there any plans to integrate the vault for instant purchases from multisafepay ?
https://devdocs.magento.com/guides/v2.2/mrg/ce/instant-purchase/
https://devdocs.magento.com/guides/v2.2/payments-integrations/vault/vault-intro.html

**Comment by Jasper-MultiSafepay** [comment]
@Darkbelg 
This looks interesting and similar to our current implementation of Tokenization.
See https://docs.multisafepay.com/tools/tokenization/
We are currently providing a similar experience to consumers in our Magento2 plugin, when you enable Tokenization in our plugin settings.

We will research if we can incorporate Instant Purchases into our plugin.
PLGMAGTWOS-355

**Comment by Darkbelg** [comment]
@Jasper-MultiSafepay Any more information about the status of the research ?

**Comment by vinodsowdagar** [comment]
Hi @Darkbelg ,

Thank you for the report.

Unfortunately, this plugin is deprecated and we are not providing support for it anymore. Please upgrade to our [New Magento 2 plugin.](https://github.com/MultiSafepay/magento2).

We have added support for Magento Vault and Instant Purchase in the new plugin and the new plugin also has tons of other improvements.
I am closing this issue for now. If you have any more comments or questions, feel free to create a new issue in the new plugin repo.
