### ISSUE TITLE
Observe 'create shipment' and 'place order' globally

### ISSUE THREAD

**Issue by evs-xsarus** [MultiSafepay/Magento2Msp#87]
Currently, when a shipment is created or an order is placed, those events are only observed when it happens in the adminhtml. If these events are thrown in the frontend, or in command line scripts, the observer isn't triggered.

Could you release a new version where these observers are changed so they are triggered regardless of the frontname the event is thrown in?

I.e.: move https://github.com/MultiSafepay/Magento2Msp/blob/master/etc/adminhtml/events.xml to https://github.com/MultiSafepay/Magento2Msp/blob/master/etc/events.xml

**Comment by JonkRuud** [comment]
@evs-xsarus Thank you for your proposed change, we will create an internal task for this to review and test. If all is working we will add this to the release

**Comment by Jasper-MultiSafepay** [comment]
PLGMAGTWOS-365

**Comment by evs-xsarus** [comment]
@Jasper-MultiSafepay could you give me an estimate when this review will be performed?

**Comment by Ruud-MultiSafepay** [comment]
@evs-xsarus This task is part of our current sprint and is already resolved internally, pending a release.

**Comment by evs-xsarus** [comment]
Thank you for the feedback, I'll await the release.

**Comment by Jasper-MultiSafepay** [comment]
We have released 1.7.0 which solves this issue.
