### ISSUE TITLE
[PLGMAGTWOS-375] Please use unguessable number for identification.

### ISSUE THREAD

**Issue by Luciferiix** [MultiSafepay/Magento2Msp#90]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Ruud-MultiSafepay** [comment]
@Luciferiix Thank you for reporting. We have created an internal task for this report and will try to review as soon as possible. Internal reference: PLGMAGTWOS-375

**Comment by Jasper-MultiSafepay** [comment]
@Luciferiix 
After analysis we decided that the impact of this can be a bit more than expected.
We will release a hotfix this week.

**Comment by Jasper-MultiSafepay** [comment]
We have released 1.7.0 which solves this issue.
