### ISSUE TITLE
[PLGMAGTWOS-418] Customer gets a reminder with a link to pay when order placed in admin by us

### ISSUE THREAD

**Issue by PiroozMB** [MultiSafepay/Magento2Msp#95]
Hi 

When we place an order in the backend of magento2 for a customer and the status of order goes on pending, then the customer gets a reminder from msp with a link to pay. We don't want them to get an email when WE place the order in backend for them. We do want them to recieve an email when they order themselves in our frontend. In magento 1.3.9 it was working fine but it's not the case now in magento2. What is the fix for this please. 

Thank you

Pirooz

**Comment by Jasper-MultiSafepay** [comment]
@PiroozMB 
Currently the customer will get a Second Chance email.
This happens 1 hour after the backend order has been placed.

We will check if it's possible to disable Second Chance when backend orders has been placed.
PLGMAGTWOS-418

**Comment by PiroozMB** [comment]
@Jasper-MultiSafepay 
But the customer recieves the email instantly at the moment we place the order in the backend. We want them to absolutely recieve no email.

**Comment by Jasper-MultiSafepay** [comment]
Could you clarify if you are talking about the order confirmation email (which is sent instantly by Magento2) or the Second Chance email (which is sent by MultiSafepay after 1 hour)?

**Comment by PiroozMB** [comment]
@Jasper-MultiSafepay 
I'm speaking about the Second Chance email of MSP and it is sending the email not after one hour but instantly after the order is placed in backend.

**Comment by Jasper-MultiSafepay** [comment]
Second Chance should only be send after 1 hour.
Could you give me the accountID, so I could check some logs on our side?

**Comment by PiroozMB** [comment]
Yes it's 704533

**Comment by Jasper-MultiSafepay** [comment]
I cannot find anything with that number
Could you send an email to techsupport@multisafepay.com, so we can investigate this further?

**Comment by Jasper-MultiSafepay** [comment]
Should be fixed with release of 1.7.0
