### ISSUE TITLE
Apple Pay support

### ISSUE THREAD

**Issue by jorgb90** [MultiSafepay/Magento2Msp#97]
These days a lot of countries accept Apple Pay as a payment option, so we should be able to offer it through MultiSafePay. Other services like Mollie and Buckaroo already offer it.

**Comment by Ruud-MultiSafepay** [comment]
@jorgb90 At the moment we can't add it to our Magento plugin because we don't offer the payment method yet. As soon as this is the case it will be added to our plugins

**Comment by vinodsowdagar** [comment]
Hi @jorgb90 ,

We have released a new version of our extension which contains the Apple Pay payment method. More information about this release can be found here:

https://github.com/MultiSafepay/Magento2Msp/releases/tag/1.10.0
